Red Black Tree
Cialyni/SPbU_python_sem2 pull request #12
Opened 2024-11-24 17:55 UTC by Cialyni

Егор Сергеевич, можно ли проигнорировать часть mypy ошибок? Ему очень не нравятся, что  у NullNode нет parent, left и right, а node может быть NullNode. Честно говоря, даже не знаю, как это исправлять. Наследование NullNode от Node исправляет большинство ошибок, но требует заполнить атрибуты в соответствии с родительским классом,  что тоже не кажется лучшим решением.

2024-11-27 11:44 UTC, SpirinEgor requested changes

2024-11-27 11:44 UTC, SpirinEgor commented on src/Commission/RedBlackTree.py
> +    right: Any
В таком тайпинге нет смысла

2024-11-27 11:44 UTC, SpirinEgor commented on src/Commission/RedBlackTree.py
> +    right: Any
Кажется, имеет смысл делать просто Optional некоторые поля. У тебя у каждой вершины точно есть key, value, а все остальное может отсутствовать

2024-11-27 11:44 UTC, SpirinEgor commented on src/Commission/RedBlackTree.py
> +    color: str = "red"
Здесь ENUM можно заиспользовать

2024-11-27 11:44 UTC, SpirinEgor commented on src/Commission/RedBlackTree.py
> +class NullNode(Node):
Как будто бы лишнее

2024-11-27 11:44 UTC, SpirinEgor commented on src/Commission/RedBlackTree.py
> +print(a)
Хотя бы под `if __name__ == "__main__":` спрячь

2024-11-27 11:44 UTC, SpirinEgor commented on src/Commission/RedBlackTree.py
> +    def _rotate_left(self, x: Node) -> None:
Кажется можно сильно проще и аккуратнее

2024-11-27 11:44 UTC, SpirinEgor commented on src/Commission/RedBlackTree.py
> +            yield node
`yield from`

2024-11-27 11:44 UTC, SpirinEgor commented on src/Commission/RedBlackTree.py
> +
Кажется надо проверить, что такого ключа еще нет. Если есть, то нам достаточно value подменить

2024-11-27 11:44 UTC, SpirinEgor commented on src/Commission/RedBlackTree.py
> +        def _deleting_fix(deleting_node: Node) -> None:
Выглядит очень страшно)

2024-11-30 20:20 UTC, Cialyni commented on src/Commission/RedBlackTree.py
Что то я вообще не понимаю, почему при одинаковой конфигурации pr wiki search у меня прошел, а тут появилась ошибка в старом тесте treap

2024-12-05 18:24 UTC, SpirinEgor approved these changes

2024-12-05 18:25 UTC, merged